# Generated by Django 4.2.1 on 2023-06-08 09:06

import appManu.oggetto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appManu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, appManu.oggetto.libro),
        ),
    ]
