# Generated by Django 4.2.1 on 2023-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appManu', '0002_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autore',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='data_pubblicazione',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descrizione',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='genere',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='prezzo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titolo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
