# Generated by Django 4.2.1 on 2023-06-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appManu', '0003_libro_autore_libro_data_pubblicazione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255, null=True)),
                ('artista', models.CharField(max_length=255, null=True)),
                ('nazione', models.CharField(max_length=255, null=True)),
                ('azienda', models.FloatField(null=True)),
                ('prezzo', models.CharField(max_length=255, null=True)),
                ('anno', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
