# Generated by Django 4.2.1 on 2023-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appManu', '0004_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='azienda',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cd',
            name='prezzo',
            field=models.FloatField(null=True),
        ),
    ]
